[versions]
agp = "9.0.1"
kotlin = "2.3.10"
arrow = "2.2.1.1"
coreKtx = "1.17.0"
composeBom = "2026.02.00"
activityCompose = "1.12.4"
androidLifecycle = "2.10.0"
materialIcons = "1.7.8"
googleFonts = "1.10.3"
koin = "4.1.1"

[libraries]
arrow-stack = { group = "io.arrow-kt", name = "arrow-stack", version.ref = "arrow" }
arrow-core = { group = "io.arrow-kt", name = "arrow-core" }
arrow-core-serialization = { group = "io.arrow-kt", name = "arrow-core-serialization" }
arrow-fxCoroutines = { group = "io.arrow-kt", name = "arrow-fx-coroutines" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "googleFonts" }
material-icons-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "materialIcons" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidLifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidLifecycle" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager" }

[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }